"""
Prompt templates for zero-shot AI text detection via Ollama.
"""

# Primary zero-shot classification prompt
ZERO_SHOT_PROMPT = """You are an expert at detecting AI-generated text. Your task is to determine whether the following text was written by a human or generated by an AI (like ChatGPT, GPT-4, Claude, etc.).

Analyze the text carefully and respond with ONLY one of these two options:
- "HUMAN" if the text was written by a human
- "AI" if the text was generated by an AI

Do not provide any explanation. Just respond with either "HUMAN" or "AI".

TEXT TO ANALYZE:
\"\"\"
{text}
\"\"\"

YOUR CLASSIFICATION:"""


# Alternative prompt with confidence (for potential probability calibration)
ZERO_SHOT_PROMPT_WITH_CONFIDENCE = """You are an expert at detecting AI-generated text. Your task is to determine whether the following text was written by a human or generated by an AI (like ChatGPT, GPT-4, Claude, etc.).

Analyze the text carefully and respond in this exact format:
CLASSIFICATION: [HUMAN or AI]
CONFIDENCE: [0-100]

Do not provide any other explanation.

TEXT TO ANALYZE:
\"\"\"
{text}
\"\"\"

YOUR RESPONSE:"""


# Chain-of-thought prompt (optional, for more nuanced analysis)
COT_PROMPT = """You are an expert at detecting AI-generated text. Analyze the following text to determine if it was written by a human or generated by an AI.

Consider these aspects:
1. Writing style and naturalness
2. Vocabulary patterns
3. Structural consistency
4. Common AI-writing patterns (overly formal, repetitive phrases, etc.)

TEXT TO ANALYZE:
\"\"\"
{text}
\"\"\"

After your brief analysis, provide your final classification on a new line as either "FINAL: HUMAN" or "FINAL: AI"."""


def get_prompt(text: str, prompt_type: str = "default") -> str:
    """
    Format a prompt with the given text.
    
    Args:
        text: The text to classify
        prompt_type: One of "default", "confidence", or "cot"
    
    Returns:
        Formatted prompt string
    """
    # Truncate very long texts to fit context window (keep first ~3000 chars)
    max_text_length = 3000
    if len(text) > max_text_length:
        text = text[:max_text_length] + "..."
    
    if prompt_type == "confidence":
        return ZERO_SHOT_PROMPT_WITH_CONFIDENCE.format(text=text)
    elif prompt_type == "cot":
        return COT_PROMPT.format(text=text)
    else:
        return ZERO_SHOT_PROMPT.format(text=text)
